### ISSUE TITLE
Need to add ability to filter main dashboard by Country

### ISSUE THREAD

**Issue by ryanwoconnor** [splunk/corona_virus#1]

**Comment by coreyamarshall** [comment]
Can this include country, state/province, county, city (where available)?

**Comment by ryanwoconnor** [comment]
This should be resolved at a Country level. I am not officially filtering on all country for all panels in the main dashboard. 

County/City level data is no longer available from JHU. 

No state visualizations are inside of the main dashboard so I'm not going to add in State filtering right now. Let's open a separate issue for a U.S. State Level Dashboard.
