### ISSUE TITLE
docs: methodology on data

### ISSUE THREAD

**Issue by Akuukis** [splunk/corona_virus#10]
Great stuff! I wish I could use it for my dashboard [Pandemic Estimator](https://pandemic-estimator.net/) but for that your API lacks documentation on methodology. I'm using JHU directly and I know what chaos it is, the most blatant example being that they provide "cumulative data" that's not cumulative quite often in practice. And the whole change of file formats, etc.

Can you please describe methodology in readme how you deal with it, especially what's going on inside `merge.py` file? What has been omitted, what has been "adjusted" and how? Thank you!

**Comment by ryanwoconnor** [comment]
Hello Akuukis,

As mentioned in the documentation:

"This package depends on a submodule from here: https://github.com/CSSEGISandData/COVID-19 which is the main source of data for the Coronavirus."

Additionally, our merge.py file simply takes the daily reports provided from the aforementioned Github repository (specifically the CSSE Daily Reports), and appends all of them onto one another. The only adjustment going on, is standardizing on field names. For example: in some files "Province/State" and in others we have "Province/State". This allows us to search commonly for "Country" Across all dates as far back as JHU provides daily reports. 

This methodology creates a massive CSV with all of the following fields:

-         "Latitude"
-         "Longitude"
-         "Country"
-         "State"
-         "Deaths"
-         "Confirmed"
-         "Recovered"
-         "County"
-         "FIPS"

_Note: Not all of these fields are filled out for all daily reports. For example, County level data only started coming in very recently._ 

Does this help?

Thank you,
Ryan

**Comment by Akuukis** [comment]
Yes, thanks for clarification. Unfortunately I can't use it because it doesn't standardize the JHU mess, for example entry naming (e.g. "France" vs "France, France") nor gaps (e.g. France-something on Mar 23).
