### ISSUE TITLE
Problem Sorting Countries by Total Reported Cases

### ISSUE THREAD

**Issue by elay108** [splunk/corona_virus#11]
Sorting the countries with most reported cases is done by "|addtotals | sort 0 - Total" on the lookup of confirmed cases. Each value in each date field is the total number of cases reported per country since the start of the pandemic. For example, China had 81,340 cases on March 26, and 81,285 cases on March 25. Adding these 2 numbers is meaningless - the addtotals returns not the number of total cases reported in the country so far, but the total of total cases reported in the country so far (per day). The sort should be done by the maximum number of total reported cases per day for each country.

**Comment by ryanwoconnor** [comment]
Elay,

Can you refer me to exactly which dashboard/panel you're referring to and include a screenshot and exact SPL? This will help with understanding better what you're referring to. 

Thank you,
Ryan

**Comment by elay108** [comment]
Yes, the dashboard is the main Coronavirus dashboard, you can look at the chart "Top 25 Countries with Reported Cases (Over Time)". 
You can see that even though the US has more cases than China, it is located beneath China.
I also added a screenshot of the statistics table, performing the search only until the table is sorted by the total field, and including only the values for the last couple of days. The result of the Total field is not the total cases in the country, but the sum of the total cases in the country per day.
<img width="202" alt="Screen Shot 2020-03-27 at 15 31 17" src="https://user-images.githubusercontent.com/7428480/77763701-876b4100-704c-11ea-8564-936c58f6da06.png">
<img width="224" alt="Screen Shot 2020-03-27 at 15 31 23" src="https://user-images.githubusercontent.com/7428480/77763705-89350480-704c-11ea-8f52-526d7d3e6891.png">
<img width="559" alt="Screen Shot 2020-03-27 at 17 00 21" src="https://user-images.githubusercontent.com/7428480/77763710-8a663180-704c-11ea-8d13-f2179686ecb4.png">
<img width="1435" alt="Screen Shot 2020-03-27 at 17 21 23" src="https://user-images.githubusercontent.com/7428480/77765667-a3241680-704f-11ea-9191-0825ab1beb63.png">

**Comment by ryanwoconnor** [comment]
I see. Completely valid. Let me work on this today
