### ISSUE TITLE
how do you set up the source type?

### ISSUE THREAD

**Issue by lachlan-00** [splunk/corona_virus#14]
I've installed this and updated from git but the dashboard is blank.

I don't use splunk often so what part of the process is missing?

**Comment by ryanwoconnor** [comment]
No sourcetypes necessary. Take a look at the README. The most common issue I see with setting up this app is people not cloning correctly. Here is the command you'll want to use:

git clone --recurse-submodules https://github.com/splunk/corona_virus.git

**Comment by lachlan-00** [comment]
done all the cloning but i'm suspecting that it's windows related as i've been renaming settings files and can't get any search.

**Comment by back2root** [comment]
The app only works on *nix, as is requires to run a shell script (as scripted input) that creates symlinks.
You would rework this on windows, using a powershell or bat script and links.

**Comment by ryanwoconnor** [comment]
I'll happily accept a PR request if a Windows user wants to create that 😀 That would be a duplicate of #2

**Comment by lachlan-00** [comment]
> 
> 
> The app only works on *nix, as is requires to run a shell script (as scripted input) that creates symlinks.
> You would rework this on windows, using a powershell or bat script and links.

I was updating them to windows versions and scripted it but the app wasn't reading the data from the lookups. i'm just pointing to the online originals now instead.
