### ISSUE TITLE
Missing KML Overlay for Dashboard "Confirmed Cases/Location Overlay"

### ISSUE THREAD

**Issue by back2root** [splunk/corona_virus#18]
## Problem Description
The Dashboard "_Confirmed Cases/Location Overlay_" is configured to use a kml overlay file which is not provided with the app.
```XML
<option name="leaflet_maps_app.maps-plus.kmlOverlay">EarthPointExcel_054900.kml</option>
```

## Error
This will throw an HTTP 404 Error + the Information from the kml will obviously not be shown on the map.

> GET https://.../en-US/static/app/leaflet_maps_app/visualizations/maps-plus/contrib/kml/EarthPointExcel_054900.kml 404
> Failed to load resource: the server responded with a status of 404 ()

![grafik](https://user-images.githubusercontent.com/9200239/78442693-b4d17380-7678-11ea-8953-650e88368563.png)

## Solution
Provide the referenced kml file with the app

**Comment by ryanwoconnor** [comment]
Apologies but this is likely an issue tied to Maps+. Can you please check out the github repo there? https://github.com/sghaskell/maps-plus

**Comment by back2root** [comment]
Nope, it's not.

See the cited Dashboard XML from my Problem description.

**Comment by ryanwoconnor** [comment]
Right I saw the cited dashboard xml. But I did not generate that XML manually. So I believe there is a bug and/or feature request you’re looking for from either core splunk or Maps+.

Sorry about that. The request is merged either way.

Ryan
