### ISSUE TITLE
Wrong numbers on Main Dashboard "Coronavirus"

### ISSUE THREAD

**Issue by back2root** [splunk/corona_virus#19]
## Problem Description
The Dashboard "_Coronavirus_" displays wrong numbers compared to the numbers you would expect and that are recorded within the CSVs from JHU.
For example the Dashboard records 0 deaths for Italy.

Some more examples:
![grafik](https://user-images.githubusercontent.com/9200239/78457365-eadb1b80-76a9-11ea-8085-81021f6de6c5.png)

## Error
The different numbers for confirmed cases, deaths and recoverd people originate from the different CSV files.
Searches within the dashboard combine these numbers using appendcols like:
 `| appendcols [ | inputlookup ... ]`

Correlating events like this will produce a valid result only if the different datasets are sorted the same way and contain the exact same number of rows.
For the three datasets this is not the case.
The different datasets get sorted, but the datasets have a different size. This will result in mixed death and recover rates.

![grafik](https://user-images.githubusercontent.com/9200239/78458645-4d84e500-76b3-11ea-97ad-acaf89028433.png)

## Solution
Rework the searches...

**Comment by ryanwoconnor** [comment]
Just resolved this. Issue with JHU Data format change.
