### ISSUE TITLE
can't run on local Splunk Enterprise on windows

### ISSUE THREAD

**Issue by int-coder-2020** [splunk/corona_virus#2]
I cloned the repo as suggested under the apps folder. The application comes up, i can view the dashboard but no data is available. I noticed that the script .sh file does a git pull which does not seem to work after enabling.  So i ran in manually from the command line, the data is downloaded and updated, however, the data still does not show up as per the documentation.

Let me know if you have any quick tips to enable this to run on windows.

**Comment by ryanwoconnor** [comment]
Working on a resolution for this. Stay tuned. Currently this is Linux support only as I am using symbolic links to connect Splunk lookups --> JHU timeseries data.

**Comment by ryanwoconnor** [comment]
Unfortunately I don't believe I'll be able to support this any time soon. I haven't forgotten about it. I just have quite a few requests coming in. Do you still require this feature?

**Comment by int-coder-2020** [comment]
No worries Ryan. I got it working by updating the .sh script, just hard coded the path to the tseries files. Thank you for starting this project.

**Comment by ryanwoconnor** [comment]
Excellent! Glad it's resolved.
