### ISSUE TITLE
earliest and latest elements in corona_virus.xml

### ISSUE THREAD

**Issue by orion84** [splunk/corona_virus#5]
corona_virus.xml contains several <search> components with earliest and latest specified, while they actually rely on the base search. See also warnings when opening the xml source in splunk web.

Also a bit puzzled by the usefulness of the 10s refresh. Since data only updates once a day.

**Comment by ryanwoconnor** [comment]
10s refresh had to do with making this supported on Splunk Cloud Gateway 1.10 which was pulled back. I'll bump this up to 10m.

Earliest and latest keep re-appearing. I'll remove.

**Comment by orion84** [comment]
Thanks for the quick explanation and great work! I built something myself before I was made aware of this, if I have further suggestions, I'll let you know!
