### ISSUE TITLE
Auto deleting when splunk restarts

### ISSUE THREAD

**Issue by sady1997** [splunk/corona_virus#8]
Hi,

First of all, thank you for this. Can I ask what is the problem behind the deletion of the content of the app except "metadata" folder after Splunk restarts? Thank you!

Regards,
Raj

**Comment by ryanwoconnor** [comment]
Hello Raj,

I have this app installed on at least 6 Splunk environments and have not experienced this. The app isn’t designed to do anything remotely destructive as you described. Can you provide me some more information about your setup? 

Thank you,
Ryan

**Comment by ryanwoconnor** [comment]
Closing this out as I have not heard back and our app does not "auto delete" anything. If this is still an issue please re-open @sady1997 

Thank you,
Ryan
